### ISSUE TITLE
Unable to use @liveblocks/react-comments/primitives

### ISSUE THREAD

**Issue by simpslandyy** [liveblocks/liveblocks#1196] opened 2023-10-05 20:46 UTC
**Describe the bug**
Not sure if this is intentional regarding the beta for comments, but I'm unable to use the primitive components (headless/unstyled components) for the `@liveblocks/react-comments` library, but I can use the styled-components just fine.

**To Reproduce**

I added the `@liveblocks/react-comments` to my project (package.json)
```
dependencies: {
...
		"@liveblocks/client": "^1.4.4",
		"@liveblocks/react": "^1.4.4",
		"@liveblocks/react-comments": "^1.4.4",
...
}

```

Then created a component to use the headless components. I tried using the sample used in the documentation

```
import { Composer } from "@liveblocks/react-comments/primitives";

function CommentTextField() {
   return (
      <Composer.Form>
        <Composer.Editor
          components={{
            Mention: () => <Composer.Mention />,
            MentionSuggestions: () => (
              <Composer.Suggestions>
                <Composer.SuggestionsList>
                  <Composer.SuggestionsListItem />
                </Composer.SuggestionsList>
              </Composer.Suggestions>
            ),
            Link: () => <Composer.Link />,
          }}
        />
        <Composer.Submit />
      </Composer.Form>
    );

}

export default CommentTextField
```

Then I get 
```
ERROR in src/components/comments/CommentTextField.tsx:1:26
TS2307: Cannot find module '@liveblocks/react-comments/primitives' or its corresponding type declarations.
  > 1 | import { Composer } from "@liveblocks/react-comments/primitives";
      |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 |
    3 | function CommentTextField() {
    4 |    return (
```

**Expected behavior**

Having access to the headless components.

**Comment by marcbouchenoire** [comment] 2023-10-06 11:22
It's definitely not intentional, we're looking into it. Thanks for reporting!

**Comment by marcbouchenoire** [comment] 2023-10-06 12:34
In your `tsconfig.json`, what is `moduleResolution` set to? [It should be set to `"node16"` or `"nodenext"`](https://www.typescriptlang.org/tsconfig#moduleResolution) for TypeScript to support import paths like `@liveblocks/react-comments/primitives`.

**Comment by simpslandyy** [comment] 2023-10-06 17:47
> In your `tsconfig.json`, what is `moduleResolution` set to? [It should be set to `"node16"` or `"nodenext"`](https://www.typescriptlang.org/tsconfig#moduleResolution) (or `"bundler"` if you're on TS >=5) for TypeScript to support import paths like `@liveblocks/react-comments/primitives`.

Oh that worked like a charm. Thank you!

**Comment by ntourne** [comment] 2024-01-05 19:35
I got the same issue on my Next.js 14 app using typescript v4.x
I already tried to update `moduleResolution` on `tsconfig.json` using `"node16"` or `"nodenext"` but I got the same issue.
Any other solution? Thanks.

**Comment by marcbouchenoire** [comment] 2024-01-08 13:27
@ntourne Do you get the exact same error with `"node16"`/`"nodenext"`, or do you get a different one?

**Comment by ntourne** [comment] 2024-01-15 21:16
> @ntourne Do you get the exact same error with `"node16"`/`"nodenext"`, or do you get a different one?

@marcbouchenoire: Thanks for the reply.
Yes, same error using `"node16"` / `"nodenext"`. Also, I'm using `"next"` `v13.4.16` (same as this [example](https://liveblocks.io/examples/comments-primitives/nextjs-comments-primitives)).
Any other thing to test?

**Comment by marcbouchenoire** [comment] 2024-01-16 13:14
@ntourne Not really sure since it seems to be pretty specific to your setup, would it be possible to make a public (GitHub, CodeSandbox, or similar) reproduction?

**Comment by marcbouchenoire** [comment] 2024-03-11 09:06
Re-closing this issue as the solution was already found (setting `moduleResolution` to `"node16"`/`"nodenext"`, or `"bundler"` if you’re on TS >=5) and added to multiple places in the docs.

**Closed by marcbouchenoire** 2024-03-11 09:06 UTC
Labels: bug, triage needed, comments
