### ISSUE TITLE
Error on deleting text in TipTap editor

### ISSUE THREAD

**Issue by barbaldo** [liveblocks/liveblocks#2047] opened 2024-11-07 22:00 UTC
I've opened a similar bug for Lexical: https://github.com/liveblocks/liveblocks/issues/2010

I'd like to notify that this same bug also happens when using TipTap

**Comment by barbaldo** [comment] 2024-11-15 11:36
Hello everyone! I see the Lexical issue has been solved, is there news on the same issue related to TipTap?

**Comment by barbaldo** [comment] 2024-11-18 09:13
@nimeshnayaju

**Comment by jrowny** [comment] 2024-11-19 19:55
It should be resolved in 2.10.11, if not, do you have repro steps for TipTap?

**Comment by barbaldo** [comment] 2024-11-20 11:17
@jrowny which package should be 2.10.11? I've got these
```
"@liveblocks/client": "^2.12.0",
    "@liveblocks/react": "^2.12.0",
    "@liveblocks/react-tiptap": "^2.12.0",
    "@liveblocks/react-ui": "^2.12.0",
    "@liveblocks/yjs": "^2.12.0",
    "@mui/icons-material": "^5.15.19",
    "@mui/material": "^5.15.19",
    "@nextui-org/react": "^2.4.0",
    "@nextui-org/shared-icons": "^2.0.7",
    "@tiptap/extension-bubble-menu": "^2.9.1",
    "@tiptap/extension-highlight": "^2.9.1",
    "@tiptap/extension-image": "^2.9.1",
    "@tiptap/extension-link": "^2.9.1",
    "@tiptap/extension-list-item": "^2.9.1",
    "@tiptap/extension-ordered-list": "^2.9.1",
    "@tiptap/extension-table": "^2.9.1",
    "@tiptap/extension-table-cell": "^2.9.1",
    "@tiptap/extension-table-header": "^2.9.1",
    "@tiptap/extension-table-row": "^2.9.1",
    "@tiptap/extension-task-item": "^2.9.1",
    "@tiptap/extension-task-list": "^2.9.1",
    "@tiptap/extension-underline": "^2.9.1",
    "@tiptap/pm": "^2.9.1",
    "@tiptap/react": "^2.9.1",
    "@tiptap/starter-kit": "^2.9.1",
```

**Comment by jrowny** [comment] 2024-11-20 18:40
sorry, I meant to write 2.11.1, which is where the fix was. I'll try to reproduce this today to see why it's still happening.

**Comment by jrowny** [comment] 2024-11-20 19:01
Tried to reproduce here with vite, tiptap, react 18.3.12, no nextjs: https://github.com/jrowny/liveblocks-tiptap-vite

but it seems to be working okay. Are you able to see the problem in this branch? I'm just adding a comment, waiting a few seconds, and resolving it. Tried with both anchored and floating threads.

**Closed** 2024-11-21 19:26 UTC
Labels: bug, triage needed
